- name: Install Nginx from source
  shell: |
    mkdir -p /opt/nginx
    cd /opt/nginx
    curl -LO http://nginx.org/download/nginx-{{ nginx_versions[nginx_selected] }}.tar.gz
    tar -xzf nginx-{{ nginx_versions[nginx_selected] }}.tar.gz
    cd nginx-{{ nginx_versions[nginx_selected] }}
    apt-get update && apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g-dev libssl-dev
    ./configure --prefix=/opt/nginx
    make
    make install
  args:
    executable: /bin/bash

- name: Symlink nginx binary to /usr/local/bin
  file:
    src: /opt/nginx/sbin/nginx
    dest: /usr/local/bin/nginx
    state: link
    force: true
