- name: Get fallback codename for MariaDB
  set_fact:
    mariadb_codename: "{{ mariadb_codename_map[ansible_distribution_release | lower] | default('focal') }}"

- name: Add MariaDB official repository via CDN
  apt_repository:
    repo: "deb [arch=amd64] https://downloads.mariadb.com/MariaDB/{{ mariadb_selected }}/ubuntu {{ mariadb_codename }} main"
    state: present
    filename: mariadb
    update_cache: true
    update_cache_retries: 5
    update_cache_retry_max_delay: 12
    validate_certs: true

- name: Install MariaDB version
  apt:
    name: "{{ mariadb_versions[mariadb_selected] }}"
    state: present
    update_cache: true
  register: mariadb_install_result
