- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: "pgdg"
  register: pg_repo
  until: pg_repo is succeeded
  retries: 3
  delay: 5

- name: Import PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update apt cache after adding PostgreSQL repo
  apt:
    update_cache: yes
  when: pg_repo.changed

- name: Install PostgreSQL {{ postgresql_versions[postgresql_selected] }}
  apt:
    name: "{{ postgresql_versions[postgresql_selected] }}"
    state: present
  when: postgresql_selected is defined

- name: Ensure PostgreSQL is started and enabled
  service:
    name: postgresql
    state: started
    enabled: true
