- name: 웹서버 설치
  hosts: webserver
  become: true

  pre_tasks:
    - name: Add nginx if selected
      set_fact:
        webserver_list: "{{ (webserver_list | default([])) + ['nginx'] }}"
      when: nginx_selected is defined

    - name: Add apache if selected
      set_fact:
        webserver_list: "{{ (webserver_list | default([])) + ['apache'] }}"
      when: apache_selected is defined

    - name: Add tomcat if selected
      set_fact:
        webserver_list: "{{ (webserver_list | default([])) + ['tomcat'] }}"
      when: tomcat_selected is defined

  vars:
    webserver_servers:
      - nginx
      - apache
      - tomcat

    nginx_selected: "1.28"
    apache_selected: "2.4.63"
    tomcat_selected: "9.0"

    nginx_versions:
      "1.28": "1.28.0"
      "1.27": "1.27.5"

    apache_versions:
      "2.4.63": "2.4.63"
      "2.4.0": "2.4.0"

    tomcat_versions:
      "9.0.85": "9.0.85"
      "10.1.20": "10.1.20"
      "11.0.0": "11.0.0"

  roles:
    - webserver
