- name: Install Node.js (version {{ nodejs_versions[nodejs_selected] }})
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_versions[nodejs_selected] | regex_replace('\\..*$', '') }}.x | bash -
    apt-get install -y nodejs
  args:
    executable: /bin/bash
