- name: Install Python build dependencies
  become: true
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - tk-dev
    state: present
    update_cache: yes

- name: Install pyenv (if not already installed)
  become: false
  shell: |
    if [ ! -d "$HOME/.pyenv" ]; then
      curl https://pyenv.run | bash
    fi
  args:
    executable: /bin/bash

- name: Ensure pyenv init in .bashrc
  become: false
  lineinfile:
    path: ~/.bashrc
    line: |
      export PATH="$HOME/.pyenv/bin:$PATH" && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"
    create: yes
    state: present
    insertafter: EOF

- name: Install Python {{ python_versions[python_selected] }} via pyenv
  become: false
  shell: |
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    pyenv install -s {{ python_versions[python_selected] }}
    pyenv global {{ python_versions[python_selected] }}
  args:
    executable: /bin/bash
