- name: Join master to Kubernetes cluster
  become: true
  shell: "{{ hostvars['localhost']['kubeadm_master_join'] }}"
  args:
    executable: /bin/bash

# - name: Label master node with control-plane role
#   delegate_to: "{{ hostvars[inventory_hostname]['first_alive_master'] }}"
#   become: true
#   shell: |
#     KUBECONFIG=/etc/kubernetes/admin.conf \
#     kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/control-plane=control-plane --overwrite
#   args:
#     executable: /bin/bash