- name: Join worker to Kubernetes cluster
  become: true
  shell: "{{ hostvars['localhost']['kubeadm_worker_join'] }}"
  args:
    executable: /bin/bash

- name: Label worker node with node-role
  delegate_to: "{{ hostvars[inventory_hostname]['first_alive_master'] }}"
  become: true
  shell: |
    KUBECONFIG=/etc/kubernetes/admin.conf \
    kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker --overwrite
  args:
    executable: /bin/bash


